import NJLogo from "../assets/logos/nhl-new-jersey-devils-logo.png";
import NYIslandersLogo from "../assets/logos/nhl-new-york-islanders-logo.png";
import NYRangersLogo from "../assets/logos/nhl-new-york-rangers-logo.png";
import PhiladelphiaLogo from "../assets/logos/nhl-philadelphia-flyers-logo.png";
import PittsburghLogo from "../assets/logos/nhl-pittsburgh-penguins-logo.png";
import BostonLogo from "../assets/logos/nhl-boston-bruins-logo.png";
import BuffaloLogo from "../assets/logos/nhl-buffalo-sabres-logo.png";
import MontrealLogo from "../assets/logos/nhl-montreal-canadiens-logo.png";
import OttawaLogo from "../assets/logos/nhl-ottawa-senators-logo.png";
import TorontoLogo from "../assets/logos/nhl-toronto-maple-leafs-logo.png";
import CarolinaLogo from "../assets/logos/nhl-carolina-hurricanes-logo.png";
import FloridaLogo from "../assets/logos/nhl-florida-panthers-logo.png";
import TampaLogo from "../assets/logos/nhl-tampa-bay-lightning-logo.png";
import WALogo from "../assets/logos/nhl-washington-capitals-logo.png";
import ChicagoLogo from "../assets/logos/nhl-chicago-blackhawks-logo.png";
import DetroitLogo from "../assets/logos/nhl-detroit-red-wings-logo.png";
import NashvilleLogo from "../assets/logos/nhl-nashville-predators-logo.png";
import STLLogo from "../assets/logos/nhl-st-louis-blues-logo.png";
import CalgaryLogo from "../assets/logos/nhl-calgary-flames-logo.png";
import ColoradoLogo from "../assets/logos/nhl-colorado-avalanche-logo.png";
import EdmontonLogo from "../assets/logos/nhl-edmonton-oilers-logo.png";
import VancouverLogo from "../assets/logos/nhl-vancouver-canucks-logo.png";
import AnaheimLogo from "../assets/logos/nhl-anaheim-ducks-logo.png";
import DallasLogo from "../assets/logos/nhl-dallas-stars-logo.png";
import LALogo from "../assets/logos/nhl-los-angeles-kings-logo.png";
import SanJoseLogo from "../assets/logos/nhl-san-jose-sharks-logo.png";
import ColumbusLogo from "../assets/logos/nhl-columbus-blue-jackets-logo.png";
import MinnesotaLogo from "../assets/logos/nhl-minnesota-wild-logo.png";
import WinnipegLogo from "../assets/logos/nhl-winnipeg-jets-logo.png";
import ArizonaLogo from "../assets/logos/nhl-arizona-coyotes-logo.png";
import VegasLogo from "../assets/logos/nhl-vegas-golden-knights-logo.png";
import SeattleLogo from "../assets/logos/nhl-seattle-kraken-logo.png";

// const TeamMap = [
//   NJLogo,
//   NYIslandersLogo,
//   NYRangersLogo,
//   PhiladelphiaLogo,
//   PittsburghLogo,
//   BostonLogo,
//   BuffaloLogo,
//   MontrealLogo,
//   OttawaLogo,
//   TorontoLogo,
//   CarolinaLogo,
//   FloridaLogo,
//   TampaLogo,
//   WALogo,
//   ChicagoLogo,
//   DetroitLogo,
//   NashvilleLogo,
//   STLLogo,
//   CalgaryLogo,
//   ColoradoLogo,
//   EdmontonLogo,
//   VancouverLogo,
//   AnaheimLogo,
//   DallasLogo,
//   LALogo,
//   SanJoseLogo,
//   ColumbusLogo,
//   MinnesotaLogo,
//   WinnipegLogo,
//   ArizonaLogo,
//   VegasLogo,
//   SeattleLogo,
// ];
const TeamMap = [
  {
    id: 0,
    abbreviation: "NJD",
    label: "New Jersey Devils",
    location: "New Jersey",
    logo: NJLogo,
    clicked: false,
    correct: false,
    position: "",
  },
  {
    id: 1,
    abbreviation: "NYI",
    label: "New York Islanders",
    location: "New York",
    logo: NYIslandersLogo,
    clicked: false,
    correct: false,
    position: "",
  },
  {
    id: 2,
    abbreviation: "NYR",
    label: "New York Rangers",
    location: "New York",
    logo: NYRangersLogo,
    clicked: false,
    correct: false,
    position: "",
  },
  {
    id: 3,
    abbreviation: "PHI",
    label: "Philadelphia Flyers",
    location: "Philadelphia",
    logo: PhiladelphiaLogo,
    clicked: false,
    correct: false,
    position: "",
  },
  {
    id: 4,
    abbreviation: "PIT",
    label: "Pittsburgh Penguins",
    location: "Pittsburgh",
    logo: PittsburghLogo,
    clicked: false,
    correct: false,
    position: "",
  },
  {
    id: 5,
    abbreviation: "BOS",
    label: "Boston Bruins",
    location: "Boston",
    logo: BostonLogo,
    clicked: false,
    correct: false,
    position: "",
  },
  {
    id: 6,
    abbreviation: "BUF",
    label: "Buffalo Sabres",
    location: "Buffalo",
    logo: BuffaloLogo,
    clicked: false,
    correct: false,
    position: "",
  },
  {
    id: 7,
    abbreviation: "MTL",
    label: "Montréal Canadiens",
    location: "Montréal",
    logo: MontrealLogo,
    clicked: false,
    correct: false,
    position: "",
  },
  {
    id: 8,
    abbreviation: "OTT",
    label: "Ottawa Senators",
    location: "Ottawa",
    logo: OttawaLogo,
    clicked: false,
    correct: false,
    position: "",
  },
  {
    id: 9,
    abbreviation: "TOR",
    label: "Toronto Maple Leafs",
    location: "Toronto",
    logo: TorontoLogo,
    clicked: false,
    correct: false,
    position: "",
  },
  {
    id: 10,
    abbreviation: "CAR",
    label: "Carolina Hurricanes",
    location: "Carolina",
    logo: CarolinaLogo,
    clicked: false,
    correct: false,
    position: "",
  },
  {
    id: 11,
    abbreviation: "FLA",
    label: "Florida Panthers",
    location: "Florida",
    logo: FloridaLogo,
    clicked: false,
    correct: false,
    position: "",
  },
  {
    id: 12,
    abbreviation: "TBL",
    label: "Tampa Lightning",
    location: "Tampa",
    logo: TampaLogo,
    clicked: false,
    correct: false,
    position: "",
  },
  {
    id: 13,
    abbreviation: "WSH",
    label: "Washington Capitals",
    location: "Washington",
    logo: WALogo,
    clicked: false,
    correct: false,
    position: "",
  },
  {
    id: 14,
    abbreviation: "CHI",
    label: "Chicago Blackhawks",
    location: "Chicago",
    logo: ChicagoLogo,
    clicked: false,
    correct: false,
    position: "",
  },
  {
    id: 15,
    abbreviation: "DET",
    label: "Detroit Red Wings",
    location: "Detroit",
    logo: DetroitLogo,
    clicked: false,
    correct: false,
    position: "",
  },
  {
    id: 16,
    abbreviation: "NSH",
    label: "Nashville Predators",
    location: "Nashville",
    logo: NashvilleLogo,
    clicked: false,
    correct: false,
    position: "",
  },
  {
    id: 17,
    abbreviation: "STL",
    label: "St. Louis Blues",
    location: "St. Louis",
    logo: STLLogo,
    clicked: false,
    correct: false,
    position: "",
  },
  {
    id: 18,
    abbreviation: "CGY",
    label: "Calgary Flames",
    location: "Calgary",
    logo: CalgaryLogo,
    clicked: false,
    correct: false,
    position: "",
  },
  {
    id: 19,
    abbreviation: "COL",
    label: "Colorado Avalanche",
    location: "Colorado",
    logo: ColoradoLogo,
    clicked: false,
    correct: false,
    position: "",
  },
  {
    id: 20,
    abbreviation: "EDM",
    label: "Edmonton Oilers",
    location: "Edmonton",
    logo: EdmontonLogo,
    clicked: false,
    correct: false,
    position: "",
  },
  {
    id: 21,
    abbreviation: "VAN",
    label: "Vancouver Canucks",
    location: "Vancouver",
    logo: VancouverLogo,
    clicked: false,
    correct: false,
    position: "",
  },
  {
    id: 22,
    abbreviation: "ANA",
    label: "Anaheim Ducks",
    location: "Anaheim",
    logo: AnaheimLogo,
    clicked: false,
    correct: false,
    position: "",
  },
  {
    id: 23,
    abbreviation: "DAL",
    label: "Dallas Stars",
    location: "Dallas",
    logo: DallasLogo,
    clicked: false,
    correct: false,
    position: "",
  },
  {
    id: 24,
    abbreviation: "LAK",
    label: "Los Angeles Kings",
    location: "Los Angeles",
    logo: LALogo,
    clicked: false,
    correct: false,
    position: "",
  },
  {
    id: 25,
    abbreviation: "SJS",
    label: "San Jose Sharks",
    location: "San Jose",
    logo: SanJoseLogo,
    clicked: false,
    correct: false,
    position: "",
  },
  {
    id: 26,
    abbreviation: "CBJ",
    label: "Columbus Blue Jackets",
    location: "Columbus",
    logo: ColumbusLogo,
    clicked: false,
    correct: false,
    position: "",
  },
  {
    id: 27,
    abbreviation: "MIN",
    label: "Minnesota Wild",
    location: "Minnesota",
    logo: MinnesotaLogo,
    clicked: false,
    correct: false,
    position: "",
  },
  {
    id: 28,
    abbreviation: "WPG",
    label: "Winnipeg Jets",
    location: "Winnipeg",
    logo: WinnipegLogo,
    clicked: false,
    correct: false,
    position: "",
  },
  {
    id: 29,
    abbreviation: "ARI",
    label: "Arizona Coyotes",
    location: "Arizona",
    logo: ArizonaLogo,
    clicked: false,
    correct: false,
    position: "",
  },
  {
    id: 30,
    abbreviation: "VGK",
    label: "Vegas Golden Knights",
    location: "Vegas",
    logo: VegasLogo,
    clicked: false,
    correct: false,
    position: "",
  },
  {
    id: 31,
    abbreviation: "SEA",
    label: "Seattle Kraken",
    location: "Seattle",
    logo: SeattleLogo,
    clicked: false,
    correct: false,
    position: "",
  },
];

export default TeamMap;
